spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    contexts: dev

logging:
  level:
    root: INFO
    com.example.minibank.reporting: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.kafka: INFO

app:
  reporting:
    executor:
      report:
        core-size: 2
        max-size: 4
        queue-capacity: 20
      reconciliation:
        core-size: 1
        max-size: 2
        queue-capacity: 10