spring:
  application:
    name: broker-clients-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:broker}
    username: ${DB_USERNAME:broker}
    password: ${DB_PASSWORD:broker}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  ssl:
    enabled: false
  port: ${APP_PORT:8080}

app:
  api:
    version: v1
    base-path: /api/${app.api.version}
  cache:
    clients:
      cache-name: clients
      expire-after-write: 5
      maximum-size: 10000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

logging:
  logstash:
    host: ${LOGSTASH_HOST:localhost}
    port: ${LOGSTASH_PORT:5001}
    keep-alive: ${LOGSTASH_KEEP_ALIVE:30 seconds}
  level:
    org.springframework.security: INFO
    liquibase: INFO