spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/broker_dev
    username: broker
    password: broker

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    com.example: DEBUG