services:
  broker-api:
    build:
      context: .
      dockerfile: broker-api/Dockerfile
    container_name: broker-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/broker_dev
      SPRING_DATASOURCE_USERNAME: broker
      SPRING_DATASOURCE_PASSWORD: broker
    #      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - "8080:8080"
    networks:
      - broker-network