spring:
  application:
    name: broker-report-import

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:broker}
    username: ${DB_USERNAME:broker}
    password: ${DB_PASSWORD:broker}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: ${APP_PORT:8081}

app:
  api:
    version: v1
    base-path: /api/${app.api.version}
  report:
    import:
      batch-size: 1
  cache:
    reports:
      cache-name: reports
      expire-after-write: 5m
      maximum-size: 1000
    report-versions:
      cache-name: reportVersions
      expire-after-write: 10m
      maximum-size: 5000

logging:
  level:
    root: INFO
    dev.eshevchenko: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus