spring:
  application:
    name: broker-report-import

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:broker}
    username: ${DB_USERNAME:broker}
    password: ${DB_PASSWORD:broker}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: ${APP_PORT:8081}

app:
  report:
    import:
      batch-size: 1

logging:
  level:
    root: INFO
    dev.eshevchenko: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus