spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:broker_dev}
    username: ${DB_USERNAME:broker}
    password: ${DB_PASSWORD:broker}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        generate_statistics: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: report-import
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "dev.eshevchenko.dto.event"

  cache:
    type: caffeine

logging:
  level:
    org.hibernate.SQL: INFO
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
    dev.eshevchenko: DEBUG